In [6]:
import pandas as pd
import numpy as np

iris_df = pd.read_csv("iris_dataset.csv")
iris_df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa

In [ ]:
iris_dummies = pd.get_dummies(iris_df["target"], drop_first=True, dtype=int)
iris_dummies.head()

   setosa  versicolor  virginica
0       1           0          0
1       1           0          0
2       1           0          0
3       1           0          0
4       1           0          0

In [17]:
iris_dummies = pd.concat([iris_df, iris_dummies], axis=1)
iris_dummies = iris_dummies.drop("target", axis=1)
iris_dummies.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),setosa,versicolor,virginica
0,5.1,3.5,1.4,0.2,1,0,0
1,4.9,3.0,1.4,0.2,1,0,0
2,4.7,3.2,1.3,0.2,1,0,0
3,4.6,3.1,1.5,0.2,1,0,0
4,5.0,3.6,1.4,0.2,1,0,0

In [24]:
from sklearn.model_selection import cross_val_score, KFold, train_test_split
from sklearn.linear_model import LinearRegression

X = iris_dummies.drop("setosa", axis=1).values
y = iris_dummies["setosa"].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
kf = KFold(n_splits=5, shuffle=True, random_state=42)

linreg = LinearRegression()
linreg_cv = cross_val_score(linreg, X_train, y_train, cv=kf, scoring="neg_mean_squared_error")

print(f"linear Regression CV: {linreg_cv}\nLinear Regression CV Squared Root: {np.sqrt(-linreg_cv)}")

linear Regression CV: [-8.88495681e-32 -6.57384088e-32 -9.44989626e-32 -8.62816615e-32
 -1.68454672e-31]
Linear Regression CV Squared Root: [2.98076447e-16 2.56395025e-16 3.07406836e-16 2.93737402e-16
 4.10432299e-16]